In Week 2, the focus is on understanding the structure and quality of the raw dataset before performing any cleaning or analysis. The Movies Dataset was loaded and inspected to examine its size, attributes, and data types. Missing values, inconsistent data formats, and potential data quality issues were identified through preliminary checks and descriptive statistics. This initial exploration provides a clear overview of the dataset and helps in planning appropriate data cleaning and preprocessing strategies in the subsequent stages.

In [71]:
import pandas as pd

df1= pd.read_csv(
    "movies_metadata.csv",
    engine="python"
)
df2= pd.read_csv(
    "credits.csv",
    engine="python"
)
df3= pd.read_csv(
    "keywords.csv",
    engine="python"
)
df4= pd.read_csv(
    "links.csv",
    engine="python"
)
df5= pd.read_csv(
    "links_small.csv",
    engine="python"
)
df6= pd.read_csv(
    "ratings.csv",
    engine="python"
)
df7= pd.read_csv(
    "ratings_small.csv",
    engine="python"
)

In [17]:
df1.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [18]:
df2.head()

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862

In [19]:
df3.head()

      id                                           keywords
0    862  [{'id': 931, 'name': 'jealousy'}, {'id': 4290,...
1   8844  [{'id': 10090, 'name': 'board game'}, {'id': 1...
2  15602  [{'id': 1495, 'name': 'fishing'}, {'id': 12392...
3  31357  [{'id': 818, 'name': 'based on novel'}, {'id':...
4  11862  [{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...

In [20]:
df4.head()

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [21]:
df5.head()

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [22]:
df6.head()

   userId  movieId  rating   timestamp
0       1      110     1.0  1425941529
1       1      147     4.5  1425942435
2       1      858     5.0  1425941523
3       1     1221     5.0  1425941546
4       1     1246     5.0  1425941556

In [23]:

df7.head()

   userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

In [26]:
df1.shape

(45466, 24)

In [27]:
df2.shape

(45476, 3)

In [28]:
df3.shape

(46419, 2)

In [29]:
df4.shape

(45843, 3)

In [31]:
df5.shape

(9125, 3)

In [32]:
df6.shape

(26024289, 4)

In [33]:
df7.shape

(100004, 4)

In [ ]:
df1.columns

Index(['userId', 'movieId', 'rating', 'timestamp'], dtype='object')

In [34]:
df2.columns

Index(['cast', 'crew', 'id'], dtype='object')

In [ ]:
df3.columns

In [35]:
df4.columns

Index(['movieId', 'imdbId', 'tmdbId'], dtype='object')

In [36]:
df5.columns

Index(['movieId', 'imdbId', 'tmdbId'], dtype='object')

In [37]:
df6.columns

Index(['userId', 'movieId', 'rating', 'timestamp'], dtype='object')

In [38]:
df7.columns

Index(['userId', 'movieId', 'rating', 'timestamp'], dtype='object')

In [40]:
df1.dtypes

adult                     object
belongs_to_collection     object
budget                    object
genres                    object
homepage                  object
id                        object
imdb_id                   object
original_language         object
original_title            object
overview                  object
popularity                object
poster_path               object
production_companies      object
production_countries      object
release_date              object
revenue                  float64
runtime                  float64
spoken_languages          object
status                    object
tagline                   object
title                     object
video                     object
vote_average             float64
vote_count               float64
dtype: object

In [41]:
df2.dtypes

cast    object
crew    object
id       int64
dtype: object

In [42]:
df3.dtypes

id           int64
keywords    object
dtype: object

In [44]:
df4.dtypes

movieId      int64
imdbId       int64
tmdbId     float64
dtype: object

In [45]:
df5.dtypes

movieId      int64
imdbId       int64
tmdbId     float64
dtype: object

In [46]:
df6.dtypes

userId         int64
movieId        int64
rating       float64
timestamp      int64
dtype: object

In [47]:
df7.dtypes

userId         int64
movieId        int64
rating       float64
timestamp      int64
dtype: object

In [48]:
df1.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [49]:
df2.isnull().sum()

cast    0
crew    0
id      0
dtype: int64

In [50]:
df3.isnull().sum()

id          0
keywords    0
dtype: int64

In [51]:
df4.isnull().sum()

movieId      0
imdbId       0
tmdbId     219
dtype: int64

In [52]:
df5.isnull().sum()

movieId     0
imdbId      0
tmdbId     13
dtype: int64

In [53]:
df6.isnull().sum()

userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

In [54]:
df7.isnull().sum()

userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

In [55]:
df1.describe()

            revenue       runtime  vote_average    vote_count
count  4.546000e+04  45203.000000  45460.000000  45460.000000
mean   1.120935e+07     94.128199      5.618207    109.897338
std    6.433225e+07     38.407810      1.924216    491.310374
min    0.000000e+00      0.000000      0.000000      0.000000
25%    0.000000e+00     85.000000      5.000000      3.000000
50%    0.000000e+00     95.000000      6.000000     10.000000
75%    0.000000e+00    107.000000      6.800000     34.000000
max    2.787965e+09   1256.000000     10.000000  14075.000000

In [56]:
df2.describe()

                  id
count   45476.000000
mean   108345.997537
std    112443.796536
min         2.000000
25%     26443.250000
50%     60002.500000
75%    157302.000000
max    469172.000000

In [57]:
df3.describe()

                  id
count   46419.000000
mean   109769.951873
std    113045.780256
min         2.000000
25%     26810.500000
50%     61198.000000
75%    159908.500000
max    469172.000000

In [58]:

df4.describe()

             movieId        imdbId         tmdbId
count   45843.000000  4.584300e+04   45624.000000
mean    96578.775626  9.937080e+05  108661.382847
std     57216.863469  1.361924e+06  112665.970830
min         1.000000  1.000000e+00       2.000000
25%     49202.500000  8.333050e+04   26502.750000
50%    108799.000000  2.839910e+05   60178.000000
75%    145270.500000  1.538311e+06  157849.500000
max    176279.000000  7.158814e+06  469172.000000

In [59]:
df5.describe()

             movieId        imdbId         tmdbId
count    9125.000000  9.125000e+03    9112.000000
mean    31123.291836  4.798244e+05   39104.545544
std     40782.633604  7.431774e+05   62814.519801
min         1.000000  4.170000e+02       2.000000
25%      2850.000000  8.884600e+04    9451.750000
50%      6290.000000  1.197780e+05   15852.000000
75%     56274.000000  4.284410e+05   39160.500000
max    164979.000000  5.794766e+06  416437.000000

In [60]:
df6.describe()

             userId       movieId        rating     timestamp
count  2.602429e+07  2.602429e+07  2.602429e+07  2.602429e+07
mean   1.350371e+05  1.584911e+04  3.528090e+00  1.171258e+09
std    7.817620e+04  3.108526e+04  1.065443e+00  2.052889e+08
min    1.000000e+00  1.000000e+00  5.000000e-01  7.896520e+08
25%    6.716400e+04  1.073000e+03  3.000000e+00  9.907545e+08
50%    1.351630e+05  2.583000e+03  3.500000e+00  1.151716e+09
75%    2.026930e+05  6.503000e+03  4.000000e+00  1.357578e+09
max    2.708960e+05  1.762750e+05  5.000000e+00  1.501830e+09

In [61]:
df7.describe()

              userId        movieId         rating     timestamp
count  100004.000000  100004.000000  100004.000000  1.000040e+05
mean      347.011310   12548.664363       3.543608  1.129639e+09
std       195.163838   26369.198969       1.058064  1.916858e+08
min         1.000000       1.000000       0.500000  7.896520e+08
25%       182.000000    1028.000000       3.000000  9.658478e+08
50%       367.000000    2406.500000       4.000000  1.110422e+09
75%       520.000000    5418.000000       4.000000  1.296192e+09
max       671.000000  163949.000000       5.000000  1.476641e+09

In [63]:
df1.nunique()

adult                        5
belongs_to_collection     1698
budget                    1226
genres                    4069
homepage                  7673
id                       45436
imdb_id                  45417
original_language           92
original_title           43373
overview                 44307
popularity               43758
poster_path              45024
production_companies     22708
production_countries      2393
release_date             17336
revenue                   6863
runtime                    353
spoken_languages          1931
status                       6
tagline                  20283
title                    42277
video                        2
vote_average                92
vote_count                1820
dtype: int64

In [64]:
df2.nunique()

cast    43019
crew    44669
id      45432
dtype: int64

In [65]:
df3.nunique()

id          45432
keywords    25989
dtype: int64

In [66]:
df4.nunique()

movieId    45843
imdbId     45843
tmdbId     45594
dtype: int64

In [67]:
df5.nunique()

movieId    9125
imdbId     9125
tmdbId     9112
dtype: int64

In [68]:
df6.nunique()

userId         270896
movieId         45115
rating             10
timestamp    20549435
dtype: int64

In [70]:

df7.nunique()

userId         671
movieId       9066
rating          10
timestamp    78141
dtype: int64